### ISSUE TITLE
Podman?

### ISSUE THREAD

**Issue by brianjmurrell** [goncalossilva/rpm-act#1]
Given that Podman is *the* supported container technology on RH based distros, any chance of supporting that with this package?

**Comment by goncalossilva** [comment]
Hey! Did you mean to open this request over on [nektos/act](https://github.com/nektos/act)?

**Comment by brianjmurrell** [comment]
Not really.  It's the packaging here that forces the removal of `podman-docker` in favour of `moby-engine`.

https://github.com/goncalossilva/rpm-act/blob/bf2792e8f214ba87a983b6eca6cd01d6d59976f9/act-cli.spec#L13

**Comment by goncalossilva** [comment]
Ah, my bad. I had completely forgotten about that line!
